[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.4"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--production=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["mongodb", "mongoose", "next-auth"]
